### ISSUE TITLE
index.js:66 Uncaught TypeError: Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by danieldanielecki** [MiniBobbo/GameOff2019#4]
The repo is different than that one uploaded to https://minibobbo.itch.io/ninja-training-simulator, many assets (level, sounds) are missing, but that's already part of the #2. More problematic is the fact that on click one of the levels to start the game returns an error `index.js:66 Uncaught TypeError: Cannot read property 'complete' of undefined` causing no launch of certain level.

**Comment by DavidMurt** [comment]
Hi @danieldanielecki 
You're right that the repo wasn't all the way up to date.  I had added the assets folder to the gitignore for some reason (it made sense to me at the time).  I've since added it back in and repushed.  Now it should be up to date.

I'm not sure what is causing your issue though.  I can understand if you were getting assets missing errors, but the code should be identical to the stuff deployed.

Make sure you run:

- npn install
- npm run watch
- npm start

That should launch a local web server and serve the game to you.  Let me know if that doesn't work and you still get the error.

Also, you can open up the developer console (F12 in Chrome) and look at the error there.  It should map the error location back to a typescript file which would help figure out what is going on.

Let me know if anything works!

**Comment by danieldanielecki** [comment]
Now it works perfectly, thanks @MiniBobbo for the quick update!
Fantastic game, worth to invest some time to study :)
